#!/usr/bin/env python
# encoding: utf-8

import os
import fnmatch


def build(bld):
    # Includes
    includes_path = ".."

    # Sources
    sources = []
    for root, dirnames, filenames in os.walk(bld.path.abspath()):
        for filename in fnmatch.filter(filenames, "*.cpp"):
            sources.append(os.path.join(root, filename))
    sources = [f[len(bld.path.abspath()) + 1:] for f in sources]

    # Define additional required libraries for the examples
    example_required = {"example.cpp": "MAGNUM"}

    # Compile all the examples
    for example in sources:
        if example in example_required and example_required[example] in bld.env["libs"]:
            bld.program(
                features="cxx",
                install_path=None,
                source=example,
                includes=includes_path,
                uselib=bld.env["libs"],
                use=bld.env["libname"],
                cxxflags=bld.get_env()["CXXFLAGS"],
                target=example[: len(example) - len(".cpp")],
            )
